module.exports={
  router:{
    base:'/abc',
    extendRoutes(routes,resolve){
      routes.push({
        path:'/hello',
        name:'hello',
        component:resolve(__dirname,'pages/about.vue')
      })
    }
  }
}